### PR TITLE
refactor!: add submodule `spark_pool`

### PR DESCRIPTION
**Pull request by ErlendT**

### CODE REVIEW

**Comment by hknutsen** [comment]
Looks like a breaking change to me, since users will have to update their module call. Agree @equinor/terraform-baseline-maintainers?

Suggested PR/squash commit:

```plaintext
refactor!: add submodule `spark_pool`

BREAKING CHANGE: remove variable `spark_pools`. To migrate your project, migrate
`azurerm_synapse_spark_pool` resources created by this module into the
`spark_pool` submodule instead.
```

**Comment by BouvetMorten** [comment]
Hi @terraform-baseline-maintainers!
When will this be reviewed and merged? 
Need some of the changes here to upgrade to latest provider 😄

**Comment by BouvetMorten** [comment]
Hi @equinor/terraform-baseline-maintainers!
When will this be reviewed and merged?
Need some of the changes here to upgrade to latest provider 😄

**Review by hknutsen — APPROVED** [review]
Looks good 👍

**Pull request merged**
